services:
  sendme-b:
    build: ./SendMe-B
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{n0n_s0n0_s1mp4t1ch3_l3_mucch3}"
    ports:
      - "1337:5000"
    privileged: true
    networks: [ ]
    
  bankmanager:
    build: ./BankManager 
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{Ar3_You_4uth0riz3d?}"
    ports:
      - "1338:5000"
    privileged: true
    networks: [ ]
  
  brng:
    build: ./BRNG
    restart: unless-stopped
    ports:
      - "1342:5000"
    privileged: true
    networks: [ ]

