services:

  lightbirdexp:
    build: ./LightBirdExp
    restart: unless-stopped
    ports:
      - "1346:8080"
    privileged: true
    networks: [ ]
    
  sendme-b:
    build: ./SendMe-B
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{n0n_s0n0_s1mp4t1ch3_l3_mucch3}"
    ports:
      - "1337:5000"
    privileged: true
    networks: [ ]
    
  bankmanager:
    build: ./BankManager 
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{Ar3_You_4uth0riz3d?}"
    ports:
      - "1338:5000"
    privileged: true
    networks: [ ]
  
  caos:
    build: ./caos 
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{th1s_1s_r3t2w1n}"
    ports:
      - "1339:5000"
    privileged: true
    networks: [ ]
  
  canary:
    build: ./canary 
    restart: unless-stopped
    environment:
      - JAIL_ENV_FLAG="CodeVinciCTF{vff4444_s31_tr0pp0_f0rt3}"
    ports:
      - "1340:5000"
    privileged: true
    networks: [ ]
  
  brng:
    build: ./BRNG
    restart: unless-stopped
    ports:
      - "1342:5000"
    privileged: true
    networks: [ ]
  
  sendmecodevinci:
    build: ./sendMeCodeVinci
    restart: unless-stopped
    ports:
      - "1343:5000"
    privileged: true
    networks: [ ]
  
  cojailde:
    build: ./Cojailde
    restart: unless-stopped
    ports:
      - "1348:5000"
    privileged: true
    networks: [ ]
  
  colosso:
    build: ./colosso
    restart: unless-stopped
    ports:
      - "1341:5000"
    privileged: true
    networks: [ ]
  
  binario_incompleto:
    build: ./Binario_Incompleto
    restart: unless-stopped
    ports:
      - "1347:5000"
    privileged: true
    networks: [ ]
  
  proxy:
    build: ./insanity-check/build/proxy
    restart: unless-stopped
    ports:
      - 1349:3000
  backend:
    build: ./insanity-check/build/backend
    restart: unless-stopped
    environment:
      - FLAG=CodeVinciCTF{n3vEr_tRu5t_4_w4f_:drop_of_blood:}
  
